### ISSUE TITLE
Rice cfg and ini settings not applying

### ISSUE THREAD

**Issue by carnage702** [emukidid/Wii64#49]
So i noticed this today
Sometimes settings dont apply to the games becuase they arent detected as being the same game 

what is rice  naming convention what is this?

{f18b591b459ba2ec-45}
Name=AERO FIGHTERS ASSAUL
i supose the last 2 digits are region but the first big number is what a rom crc?md5?hash? becuase this makes many of thesettings not being applied becuase games dont match and there for get no settings.sure rice makes an entry on the ini latter but you need to go look and copy the setting to your version which is very troublesome so you can maybe code it to use gameid to apply settings?

**second** there are setting in the ini that dont exist or have diferent names maybe? on the ini? does changing those settings do anything?or only the ones that are on both rice cfg and rice ini are actualy coded in?or they are all coded in but some are hidden and dont appear on the ricecfg file?

BONUS
i found out why fix94 rice recompile does that to yoshi story and probably more games yoshi story has a ini saying
RenderToTexture=3

and for some reasin your rice doesnt consider the 3 being good? if you change it to 2 it will do what fix94 recompile version does which is fix background, why does fix94 recompile of rice recognizes the 3 and yours doesnt?  afaik the rice settings go from
 0=use default cfg value
1=off
2=on
3=?
4=?

some go to 3 and 4 so maybe you didnt implement those?

**Comment by carnage702** [comment]
if you play beetle adventure racing and then load another rom and then close wii64 you will notice like every game ricevideo will creat a new ini entry on the ricevideo.ini files on the bottom and then copy the entrys on beetle adventure racing to there and it will work like fix94 one does, im guessing fix94 made so the patches applyed with gameid or something? becuase right now they dont apply for most roms and i use good ! roms so no idea what those roms on ricevideo are actualy.

**Comment by emukidid** [comment]
yeah I think I know what the issue here is, I'll look into it, it's not that we don't have FIX94's changes (I check with him to see if he'd not pushed some changes), but rather that config lookups are broken in some way, similar to what I'd found with 15ca7353dd3e76d74bd6d07253de9ccaf16d5d08

**Comment by NintendoManiac64** [comment]
I don't suppose is related to the issue I'm running into where trying to load the the game will give a crash dump unless the RiceVideo.cfg and RiceVideoLinux.cfg files do not exist?

(that is, I have to delete them; but then after successfully launching a game it then creates those .cfg files and then the problem comes back when trying to launch another game or the same game again)

**Comment by carnage702** [comment]
> 
> 
> I don't suppose is related to the issue I'm running into where trying to load the the game will give a crash dump unless the RiceVideo.cfg and RiceVideoLinux.cfg files do not exist?
> 
> (that is, I have to delete them; but then after successfully launching a game it then creates those .cfg files and then the problem comes back when trying to launch another game or the same game again)

works fine for me, i use it to test dozens of games and even change settings to try and correct stuff and never had any issues, i use those files and such, make sure you have the correct releases of rice and not the first try of emukid where memory leak was a thing. or maybe your sd card is getting too badly corrupted or locked somehow.

**Comment by NintendoManiac64** [comment]
> make sure you have the correct releases of rice and not the first try of emukid

...the first try?  That implies that there were multiple tries, but I'm only seeing a single version from 2018-02-16 on the releases page (which is the version I'm using).

**Comment by carnage702** [comment]
> 
> 
> > make sure you have the correct releases of rice and not the first try of emukid
> 
> ...the first try? That implies that there were multiple tries, but I'm only seeing a single version from 2018-02-16 on the releases page (which is the version I'm using).

that is outdated and had boxbin bugged that crashed he uploaded this on one of the issues
https://github.com/emukidid/Wii64/files/5472234/wii64-master.zip

use the dols that have wiivc on the name even on wii, they have correct speed limiters.

**Comment by saulfabregwiivc** [comment]
have the same issue with latest Wii64 from 2020. The custom ready-to-use RiceVideoLinux.ini files i use isn't used but erased and "prepared" by emptying it. I don't want Wii64 to empty that file but Wii64 should take the values from a custom ready-to-use RiceVideoLinux.ini files automatically, instead of erasing everything of it and create new ones. Can fix this @emukidid and also add the other fixes and features that @FIX94 did?

**Comment by saulfabregwiivc** [comment]
have the same issue with latest Wii64 from 2020. The custom ready-to-use RiceVideoLinux.ini files i use isn't used but erased and "prepared" by emptying it. I don't want Wii64 to empty that file but Wii64 should take the values from a custom ready-to-use RiceVideoLinux.ini files automatically, instead of erasing everything of it and create new ones. Can fix this @emukidid and also add the other fixes and features that @FIX94 did?

**Comment by emukidid** [comment]
Can confirm that 15ca7353dd3e76d74bd6d07253de9ccaf16d5d08 fixes this, closing.
